on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docker hub"
        run: docker login --username mooazhassan --password dckr_pat_YxWjqvDaP4LLT47HuQQZbxv-zZ0




